// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyBuddy.Data;

#nullable disable

namespace StudyBuddyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250502200911_AddLikesSupport")]
    partial class AddLikesSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("StudyBuddy.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("StudyBuddy.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StudyBuddy.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudyFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StudyFieldId");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("StudyBuddy.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1679d7f6-214b-41e2-8a42-d0ba95639cc7"),
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("0876d319-e5d9-444b-829e-0e348b6b11e9"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("c987b2f4-3ec5-4a8e-a2e8-67447fe74046"),
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("9f62316b-3ef7-457c-8302-4cc7ca8727f9"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("86bc0ee5-609b-4f3f-9387-87bcbf1cb317"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("90b7df75-af42-4d16-80d6-d28bc7b3b222"),
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("8ee4a6b5-f397-4478-933c-91f3d3d21c60"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("0ee4bdeb-7211-4cb6-bc63-90e776d9b4a4"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("4d0fe7f8-6b1a-4e7c-93e0-59bc7e2db973"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("4ce8512b-f467-4aa3-bfb0-be7adcab28d9"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("11805ce3-161b-4c0d-9b0c-cb1297d1465b"),
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("1f61fe25-4382-4fef-b9cf-dc72971b3c94"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("aed3feae-c3f1-4dbd-b8e6-e18dd34657ef"),
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("988d7265-c705-4c47-8318-a2d78134164d"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("50099bce-c503-4fcf-bcab-43e68303882b"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("e7b9eba5-809b-4e8a-87fe-73d4105c5720"),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("960d0ef3-1166-4eb4-92d6-5b32fcd86518"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("bd1e29f0-1a2f-4dcd-8dd5-13bebaa9c365"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("00926e50-ef7f-4e88-a3c3-425c62c6fd67"),
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("d2b1eeed-6454-4c91-a5af-afcb8e50462d"),
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("b4b31b57-1ca0-43e9-b441-28cb427b6b87"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("ae35ae4f-303d-42b2-bb8d-2d97ace904f7"),
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("439ff6be-a892-4550-9fef-0fac2ba9bca2"),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("ab298ced-6170-4b26-b949-2db7428c6ae5"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("208441ec-e8c3-440b-9b41-b06b63adcd7c"),
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = new Guid("374ca0ba-a756-4cab-9b6e-c0c9b20c1cc9"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("ead102c8-200e-4aff-b76e-76a45800e935"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("7c0b7cb7-edd7-42ae-aef9-99ae18f16358"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("0db645b5-ef7b-4f6c-acf9-adb096648b82"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("8c42745c-55f1-4f7b-8935-9efde667830b"),
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("8eb4d135-82d7-4b4f-80d2-4552a9bb10dd"),
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("ab7b489a-e158-44c6-b18a-c4967f90c346"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("c132caf8-7ccd-4578-9391-012c08b6d32d"),
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("1f2c5ba4-50ce-431f-a0e1-3070fc59a273"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("8f4e3d52-f18b-4961-a949-2562d941afac"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("30cd1120-52aa-43ee-b01c-91ee726e9dfa"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("0c4ff2a2-d66c-4df7-ae16-5fcac264aff2"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("dd944089-8e06-47a1-9482-3965083bd532"),
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("7d79e91c-fc7c-45e0-9038-73c2cbcc04a4"),
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("ffc35dba-7c31-48d0-8041-59a220fedeb7"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("a0e41886-15bb-4462-b983-e69c969a2c07"),
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = new Guid("21f9e6f8-f526-4590-9e64-eb810086efdb"),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("bdaaa00e-b561-4dad-b64c-bdafe898e6b2"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("c4b8d43c-9b14-4151-a75d-6105af1278db"),
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("15520e6c-49b3-4b81-b6b0-6f6c04611196"),
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("0f973119-88fa-466c-8e68-3c2d4bff1d1b"),
                            Name = "Democratic People’s Republic of Korea"
                        },
                        new
                        {
                            Id = new Guid("a2da9ce5-baf4-4864-9c8b-b761291b70b8"),
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("3fb04a39-0d74-41d4-8648-1513c45fd4fe"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("d690f1fc-7203-401e-818a-8aabac9841d7"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("14abda48-c54d-4022-981a-bc2bb728c04c"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("5e6649b9-7f1e-4c4e-be85-28a141ecc8b4"),
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("3b7d9e62-d9bb-484e-9ef4-91f1ee9ab5dd"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("59ea932e-ca4a-4d13-b8f2-6dd0cd07891f"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("2e71e22d-b63b-4b8a-ae20-8fb19162fdf3"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("69feee23-56f1-4af7-accf-37cafdacfe63"),
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("dc7f09d0-73ad-4070-b728-bebd1e33ae39"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("ab3fe895-bf1b-44b4-8ceb-ff318239fbba"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("2758fc3a-b0b0-4ca1-aac6-7dcba6c57dc3"),
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("e49c11ea-5e96-4a35-953b-1d59821a7458"),
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("cfcb3e96-39e6-4e52-9923-f26dbb1a5e0d"),
                            Name = "Federated States of Micronesia"
                        },
                        new
                        {
                            Id = new Guid("3e75ac06-5a06-4f34-ad62-89f681070ff1"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("9ea3bb1a-bd6c-48e6-9b97-71b10e365091"),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("47f2d792-2634-4cc4-a8a2-21ad1169a2c3"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("c660f5f0-b500-4355-b2ed-7bcd8b07cb80"),
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("2ae387b5-77fe-4a66-8d3f-8fe0ddd690a2"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("06aab717-f14c-43cf-84ab-0522e616ca16"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("a3af8343-8813-43aa-bcb6-bc1c07c87cab"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("603b3c77-44cc-4e8f-8b50-3448d4f6ddd5"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("575c4c55-72a4-4d15-8f78-2ab48031f262"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("a055f399-f351-436a-83ac-ca2660f4013d"),
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("d777c2e3-7421-4192-9c4f-99510087005a"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("8044cf2e-4a4d-4f1c-a36b-9aca16b2b400"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("c713c17e-297b-4055-b19f-6f1d0bec64f5"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("5e2abd72-a27a-49e0-ac32-b042212d324e"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("8060cb16-40ff-40ac-8c67-4c9d623f0cf0"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("eebb74b9-b96e-420e-8057-f3833a83ab19"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("fa9304f2-cd69-44f7-8595-20ae4a162bb5"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("01081196-cf53-409f-87e7-e2509f354afb"),
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("d361efcb-4e99-43bc-aa6e-6e08bb5f6fe6"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("6ee0dee2-f1df-48d5-be90-8ec3ebb2ffd5"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("8e2ad752-ccc1-42f7-bc3b-3492b7c21e74"),
                            Name = "Iran (Islamic Republic of)"
                        },
                        new
                        {
                            Id = new Guid("2148ebae-89ff-4402-bfc9-52d80dbcc52e"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("b3f178d0-2f39-4f18-bfa2-a006aeda189b"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("3f24a2bf-79eb-4f88-b9c5-74aedb4190f1"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("0ccd1514-ad61-4ef1-93c0-5a370e56b65d"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("039ad93d-07b9-46d2-8d60-b91ab3658487"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("9bafa1dc-1972-4a4a-9734-5a68cfb78959"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("f9c3269b-ba8f-4869-a832-74b1007f8297"),
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("65e94a04-7c83-431a-b194-8c1a8a72fc66"),
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("9023124b-5d20-4e44-827a-8f0938dd220d"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("4c72e608-f633-462e-88a2-363df3bba7b9"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("042e5f3e-a51a-4f57-82cc-f1a0972059f4"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("c3f811d0-d15e-4245-a6b7-6e7b3acf9def"),
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("354aad74-08d5-4ff3-9026-4f770f7de1d1"),
                            Name = "Lao People’s Democratic Republic"
                        },
                        new
                        {
                            Id = new Guid("91f73201-95b5-437d-9b29-9457502c4fd4"),
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("24f652c2-9e88-4870-80b9-b6d6b973c047"),
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("3d61c5c5-efae-4bdc-a074-ee0266a347ce"),
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("e5e57bbf-7172-43f5-a6c8-ecc6f0c2586a"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("32ead4d1-353c-46c6-abf1-6e7cf56f5abd"),
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("992d7ad2-123a-4001-a720-28b9178ab195"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("d7d1526c-b1fb-4c5a-897f-9f3c60ea3981"),
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("1a7da87f-530d-419f-94d8-5c05b73c7f42"),
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("ca4477d0-3c8a-4256-8f49-fc0388af990f"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("1a54228c-ddf3-4301-b402-ea0c5f8878e9"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("85d1006e-1b26-46f8-903e-098e2df055e1"),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("d9d26a18-2fea-4ae6-a9c2-59e01e93dde0"),
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("f8686215-944d-4bf5-a9b3-adeb733ff6ff"),
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("6d417f7e-f2b5-48c6-84dc-5715e941c32d"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("9775a898-64e1-4034-a515-db5fc51821ed"),
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("0945205e-0afe-4378-8755-26459ab85856"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("c5336635-fe4e-4ac4-ae0c-4e7110dde288"),
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("2bb8cf85-c90f-425c-a827-a4d1e70a4cb0"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("9864a6dd-c333-4314-8198-0741defbec9e"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("9d36c588-810b-45e9-9369-fd4d7ee70192"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("d36ae384-312a-4b8b-af91-d1e66f90122f"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("18559531-154d-45dc-9bae-3504922c2190"),
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("e8cf8c54-77af-4f1d-bdf5-191580b90256"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("883b8032-1739-466d-87a7-272596e936bb"),
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("7e2ac274-7061-4ae8-b1cc-b6adbfb826c9"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("4219279b-f2ae-4288-b4a4-2a6e4f6402a8"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("a30a6d44-7be6-4f00-80c4-ae3bea456e4f"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("ed896366-83f1-4f17-8bd3-f04a71ba1451"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("73ba5291-0c12-4769-ac78-c4ebe84bc468"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("608d5936-d44f-4a5d-ba31-97468e8dccf2"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("709adcea-0db8-47e8-b16f-b5966695960e"),
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("7ae91a97-ab41-4232-af41-909b4f340ebe"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("b2130bc6-6ec7-471a-8f63-dece185386c6"),
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("20fca5f0-72a4-4994-9326-b1a173c5e499"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("a50ade69-7008-4ea5-82ea-85665e675908"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("275e5ce0-6070-4e73-a5ef-e3a847f28f48"),
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("125c86fb-d231-4cfc-91fd-e31974344757"),
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("c322641d-ac85-4866-b49a-3c40a7ff81b4"),
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("335df8b7-7383-4da9-9fda-09bddc8204d7"),
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("5cc2db7d-6d33-4f8e-9123-d21c876c125d"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("08258e7f-0c9f-4989-af5e-bf9a19c0c21d"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("316c1fc2-b2e9-4617-92e6-2508fac91163"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("2fa97f82-953a-4739-831c-e8faa408dbf2"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("f910b420-d72f-4236-a37b-37b272490a4d"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("3c85af10-6e9b-4a7e-92ec-c7f097753bc6"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("91c42a9b-a0d9-4cd8-9b8d-c3480f939104"),
                            Name = "Republic of Korea"
                        },
                        new
                        {
                            Id = new Guid("6ecf2114-2e74-43e3-ad8c-96737c3b5f90"),
                            Name = "Republic of Moldova"
                        },
                        new
                        {
                            Id = new Guid("cc0dd72f-9bcc-471b-ba82-d7885fb67951"),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("583fd9ba-eba9-48ef-be48-bab6c1686ae7"),
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = new Guid("69bf3aa4-ae66-4baf-91f3-7cd520591759"),
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("5a18e947-66f0-4b86-9f74-cd027be3f1f9"),
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("b3d3aa21-d205-4c7a-975c-3659e977eb30"),
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("fbda51f3-1ba2-4c5d-bbae-2fbfa5ec98b8"),
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("5eadea43-4424-464c-bac1-36defeaa73df"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("d68917ec-92b1-43aa-9431-7328c69e5aeb"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("26ac99f2-08ae-4192-8cda-5bb6be76d0f9"),
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("c60c930e-877a-4344-bd52-cceb496e1690"),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("97caad11-4357-4f63-941f-9bada9517033"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("e436712c-4776-49f9-8916-e00cac73f9c8"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("0a0e5fb1-320f-45a5-b01d-13d2b676b8d9"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("64398c19-3f18-4b49-b1c0-662e183f0685"),
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("3c164dfc-eb34-4e68-815f-9768dc8acc33"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("0de77513-c152-457e-b14d-c2ce68e2f31f"),
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("0dc5896c-bc15-4bcc-a6a3-281b56270fb2"),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("707f57f5-d230-4089-9e7e-5371140bd7d6"),
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("c5d1c101-640c-4a6d-b90d-e9b6676044ea"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("66a98f59-7c59-4856-b18e-32d62fb34dae"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("d45cdf54-d283-41ad-aee9-6bbd53819bdd"),
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("57233a50-3c59-47b4-b7e3-b00eab91e8a0"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("e56dbe12-2024-483c-a612-e1edf120ca6a"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("80c0a9e1-b285-4b92-a23f-bf2b10e31373"),
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("300ad602-4aed-45a1-b4d6-f919734a729b"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("81535c1e-ee2d-46e4-94a1-06a960c4b0d5"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("085f16a7-fe97-425a-8a20-94fdbebe83bb"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("67a7f1b1-d894-4d86-bda2-ae70d2a40f52"),
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = new Guid("e409ff94-4019-48a1-b50f-91873490150b"),
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("4998590e-fb4e-4cde-90be-ff67386974fe"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("a215db0b-869d-4796-a5be-ac07340e5124"),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("ff3b04fa-cad7-4754-8cd5-82c88753a8f2"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("2e4677e2-71ea-4614-a908-25463ba11a93"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("7dfe52ae-7081-4316-a236-c7ca73822373"),
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("36da42c7-4795-4dec-afc8-8407995f3c9f"),
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("6e179037-1ba8-4fc5-9704-7a4d2fa3fed9"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("00fe4ab0-3ee7-4dc8-ba23-8ccd0579b770"),
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("5baca497-a1ff-48a2-94c7-1b68aa5f6f17"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("b71de3bd-7be3-40ea-8135-6e3a36d264e5"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("fd2e5eae-1b4d-49da-9378-dc6558d13de1"),
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("1ef84345-4bb5-4f26-af3b-dca159eeea7e"),
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("2ad67343-15c6-4caa-bf60-f831951a6320"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("ae820a1f-2032-466d-928c-73e06629ff1f"),
                            Name = "United Republic of Tanzania"
                        },
                        new
                        {
                            Id = new Guid("421524f0-ae18-4521-8831-138262d2a1ac"),
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = new Guid("62976af8-1d3b-4807-ae94-69fb8d3e5646"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("319def8c-0cc8-40a3-b36b-a537c904ca88"),
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("29e5828c-e189-44a3-8fda-e15408d75dbd"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("d78437ff-bfd1-4d5c-ab99-e4c88f1a7484"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("1bf49bc2-2bd5-4d44-8e2f-e5f222083bec"),
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = new Guid("040b4896-f587-4564-a079-12f5186590e9"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("b33d5339-a7c9-44a1-a162-6d011cf0c562"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("09cff4a5-2611-4807-9c4d-69a4cded5100"),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("StudyBuddy.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("StudyBuddy.Models.JobRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobRecommendations");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpertiseField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentorship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenteeId");

                    b.HasIndex("MentorId");

                    b.ToTable("Mentorships");
                });

            modelBuilder.Entity("StudyBuddy.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StudyBuddy.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("StudyBuddy.Models.StudyField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyFields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d101ae08-d91e-4a00-8191-8ecb973827e4"),
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = new Guid("5d619d2a-d539-40b9-b2ba-493fd3a5e1b6"),
                            Name = "Electrical Engineering"
                        },
                        new
                        {
                            Id = new Guid("8d136176-9691-4380-8c11-9ea23eb87a69"),
                            Name = "Business Administration"
                        },
                        new
                        {
                            Id = new Guid("0b844c42-8b31-4503-94f1-6768264c2672"),
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = new Guid("aa3570b0-fd63-4966-b136-bb9a7f132f84"),
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("37312de3-f9b8-479f-ad15-d9cf6a31959a"),
                            Name = "Law"
                        },
                        new
                        {
                            Id = new Guid("a6113287-9276-4fde-b8da-bb859c0d453d"),
                            Name = "Biology"
                        },
                        new
                        {
                            Id = new Guid("7876b2aa-3133-4ce4-a7e4-5d60cccbfc2a"),
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = new Guid("6323ff82-ad01-4177-a223-9bcc2273eb7c"),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("3a55ae2f-9da3-4aba-be35-404ca54fcf1d"),
                            Name = "Economics"
                        },
                        new
                        {
                            Id = new Guid("87b68467-f7c1-4146-8a3b-7cf21273b6bb"),
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("54822217-4079-47fa-837f-2470f63a61cd"),
                            Name = "Mechanical Engineering"
                        },
                        new
                        {
                            Id = new Guid("9319c3ef-0ff4-40bf-bdfa-f55f66eb8305"),
                            Name = "Civil Engineering"
                        },
                        new
                        {
                            Id = new Guid("679f46a0-1190-4d68-be59-ab5ce2711deb"),
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("f409b97e-2fef-486b-a7f1-3d2168027313"),
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = new Guid("0a793301-97f7-4aa4-8b47-0d257169b81a"),
                            Name = "Nursing"
                        },
                        new
                        {
                            Id = new Guid("b94850c6-caf3-494f-8e82-0d174312f892"),
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = new Guid("3843989c-9920-4e31-87b8-d42acf5f8a50"),
                            Name = "Veterinary Medicine"
                        },
                        new
                        {
                            Id = new Guid("1effde65-563d-4e54-811c-940a819ede36"),
                            Name = "Environmental Science"
                        },
                        new
                        {
                            Id = new Guid("9b378a05-2c2e-4052-b819-daeedaf62488"),
                            Name = "Sociology"
                        },
                        new
                        {
                            Id = new Guid("7e84fc0b-ae40-4f03-b194-ed8411c81e67"),
                            Name = "Anthropology"
                        },
                        new
                        {
                            Id = new Guid("5ab287a4-30d3-4283-8a86-22b0cd110592"),
                            Name = "Political Science"
                        },
                        new
                        {
                            Id = new Guid("6fd4b7f1-59da-4743-ac33-8faa14738d5c"),
                            Name = "International Relations"
                        },
                        new
                        {
                            Id = new Guid("d69adfdb-2f5b-4efb-a0c3-963036bead2c"),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("ab44123c-1be4-4ab3-8a2f-397dedf2d15d"),
                            Name = "Special Education"
                        },
                        new
                        {
                            Id = new Guid("0c796913-a32f-44fc-8598-0ba30d0e799e"),
                            Name = "Linguistics"
                        },
                        new
                        {
                            Id = new Guid("8391fcca-b2a9-41bb-927a-738f18d3eede"),
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = new Guid("7717643f-7778-4192-a1c3-105807184508"),
                            Name = "Theology"
                        },
                        new
                        {
                            Id = new Guid("a27e32b4-4f0a-4736-ae3c-1014fc081baf"),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("0e063e3e-363d-419a-aedb-cc5c9b2fe306"),
                            Name = "Art History"
                        },
                        new
                        {
                            Id = new Guid("6ca5fa68-94be-43eb-9295-fdc814293281"),
                            Name = "Visual Arts"
                        },
                        new
                        {
                            Id = new Guid("0893b214-ab0b-4c56-a2cd-0be2539da1cc"),
                            Name = "Film Studies"
                        },
                        new
                        {
                            Id = new Guid("8f9b7e11-4dcc-4d06-a09f-3a792bfe993e"),
                            Name = "Theater"
                        },
                        new
                        {
                            Id = new Guid("2a5cc999-7c87-46c1-ab64-cc9bedd99031"),
                            Name = "Communication"
                        },
                        new
                        {
                            Id = new Guid("ebf8f911-889a-4ebf-9866-78f2500bcfb7"),
                            Name = "Journalism"
                        },
                        new
                        {
                            Id = new Guid("89f38dd7-977d-4962-8c2c-3c3e536ec78d"),
                            Name = "Public Relations"
                        },
                        new
                        {
                            Id = new Guid("0deae631-3331-47af-9390-2238cdb4b014"),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("669c938a-b323-4cc1-97e1-51a6c49089c2"),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("3de7358d-6897-4509-aac3-c303e6c53723"),
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("7d810e15-6522-473d-89c8-597915329db2"),
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("e391753b-0c7f-418c-adfb-35371d5b140e"),
                            Name = "Supply Chain Management"
                        },
                        new
                        {
                            Id = new Guid("e67389fc-6fbf-425a-9b05-21e7ce65b227"),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("27c63995-db06-4671-82f4-d26802377667"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("3f4be2d4-5b09-4620-a25d-12fd8ab0bd69"),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("8532ba31-0f26-4d16-943b-85baac4aa4e3"),
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = new Guid("f984a2f6-4d8e-4891-8705-20327814c821"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("40053e17-de52-4fd5-b2d9-6bbd35964b89"),
                            Name = "DevOps Engineering"
                        },
                        new
                        {
                            Id = new Guid("e533ff98-d8a6-42cd-b7db-22a4014a403f"),
                            Name = "Fullstack Development"
                        },
                        new
                        {
                            Id = new Guid("b880a956-f0d4-445c-8c94-5ec326ed42ae"),
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("d25badf3-7fe9-4b37-99e3-3989d05a59c7"),
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("cc179dc6-4252-4170-913c-b5359dbaa43b"),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("6c318803-de4f-41bb-8c9a-34e33a82a8b2"),
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = new Guid("154bbaa3-417c-41dd-8072-bb5646ebaee3"),
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("4fc3bdbe-27e1-46f2-96ca-b3dc97ab9742"),
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("e96122fc-1d2f-46c6-8d85-1409d110594b"),
                            Name = "Animation and Multimedia"
                        },
                        new
                        {
                            Id = new Guid("5982c082-e80d-4ca2-b4a3-301cb5381d33"),
                            Name = "Interior Design"
                        },
                        new
                        {
                            Id = new Guid("73322c04-7609-465e-81c6-b4ad027a1121"),
                            Name = "Fashion Design"
                        },
                        new
                        {
                            Id = new Guid("5efdd57f-8b29-4673-b0a0-1388dea5a65a"),
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("9ed5dede-b783-4e86-9836-563ce904145b"),
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("6c6a6610-342c-45dc-af06-cb8356114825"),
                            Name = "E-commerce"
                        },
                        new
                        {
                            Id = new Guid("6315bfa3-e9b5-4e59-bbd7-0d07f788e244"),
                            Name = "Business Intelligence"
                        },
                        new
                        {
                            Id = new Guid("04d3c264-f919-4396-ae1a-334367b6f00b"),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("679bfe60-47ea-4790-a436-4d86fcdfd2bf"),
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyField")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5dccc538-9e4c-459b-8b47-b703f0d39611"),
                            City = "Tel Aviv",
                            Country = "Israel",
                            CreatedAt = new DateTime(2025, 5, 2, 20, 9, 11, 129, DateTimeKind.Utc).AddTicks(3466),
                            Email = "admin1@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "One",
                            Location = "Israel",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("f511557c-f69f-42ee-be11-d81cea91b2bf"),
                            City = "New York",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 5, 2, 20, 9, 11, 135, DateTimeKind.Utc).AddTicks(692),
                            Email = "admin2@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "Two",
                            Location = "USA",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b571071b-1685-4a83-9ab0-e855f71c42e6"),
                            City = "London",
                            Country = "UK",
                            CreatedAt = new DateTime(2025, 5, 2, 20, 9, 11, 135, DateTimeKind.Utc).AddTicks(1059),
                            Email = "admin3@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "Three",
                            Location = "UK",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("LeaderboardEntry", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Like", b =>
                {
                    b.HasOne("StudyBuddy.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Activity", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.ChatMessage", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StudyBuddy.Models.Comment", b =>
                {
                    b.HasOne("StudyBuddy.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.HasOne("StudyBuddy.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.StudyField", "StudyField")
                        .WithMany()
                        .HasForeignKey("StudyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("StudyBuddy.Models.Friendship", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentor", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentorship", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Mentee")
                        .WithMany()
                        .HasForeignKey("MenteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("StudyBuddy.Models.Notification", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Post", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.HasOne("StudyBuddy.Models.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("StudyBuddy.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Friends");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
