// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyBuddy.Data;

#nullable disable

namespace StudyBuddyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250502150757_AddCreatedAtToPosts")]
    partial class AddCreatedAtToPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("StudyBuddy.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("StudyBuddy.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StudyBuddy.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudyFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StudyFieldId");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("StudyBuddy.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fed50e9-32c2-42ed-8144-9a976983d035"),
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("96327cfd-3b47-4bb6-a7f4-c7e557d35d4b"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("828b2b9c-0cef-4231-89b1-8a42ce246d7e"),
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("52f27208-806a-4f65-887e-551a268b4bdc"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("abd3413f-56e0-4873-b299-2c953fa1eba6"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("ff836b90-aa07-4b13-bd90-429ed0432257"),
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("83e3416d-3c88-41fa-abb3-8a4febc8e245"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("fea7385c-bac1-4736-bc5e-cc6b90be1abb"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("c92b0873-9b89-45fd-b999-b064f7f8eea9"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("da03d736-0e28-44b0-961e-706e5fb78661"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("d0703570-291d-40d0-a75d-9806c13a63bd"),
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("2cea81b7-8c4e-47ce-b65b-4e03acd78af8"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("a70cd9b1-df14-4b3c-9ba9-3a9ad703ae3f"),
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("03123ad7-6aff-4bb3-948a-883440384757"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("b5d54b46-5f4b-4c3e-a14b-3ab14510d4e4"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("369c95d6-d52f-4a2d-89d2-2241b891cf25"),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("a36b0a95-651b-499b-880e-78c042d77dd8"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("7a71b568-1833-4625-8c11-805b0db3beaf"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("5d4d0723-8c72-4bbb-9f7f-6cfa3c7a2b29"),
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("0def300f-7c20-4e88-ac4f-d72c5a3b39dd"),
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("450ad9fc-e045-4e61-b5de-d8ec9a2e5b35"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("1614ee42-da03-4fc5-bd6a-9ee6ba0303cc"),
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("5686e74d-b4c0-4e1d-9b7e-bbf4288dd63c"),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("c69026d0-2fd6-431e-8190-c0716cd7797d"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("4be2557b-964c-4292-a69b-f60a997828f4"),
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = new Guid("a40003ff-fe9d-414f-9033-64ff50a122f5"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("ef60e426-9dbf-475a-89a9-9291c9a56b61"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("1a5cead8-0d24-4652-abe5-223216b1d301"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("96ac9534-e297-4f01-a9b5-ebf4efc76ca7"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("996a8b2a-020c-4677-98a9-29caf89ecbf4"),
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("6ece80d5-787f-42c4-b488-944ff0c58157"),
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("fb6bca2a-eff0-441e-8e87-12576cb722af"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("4fde3d70-bca7-4920-9c24-d5a325fb0449"),
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("a6b59aaf-0746-4437-a723-8cc80d704305"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("3d8dc286-cefc-4384-96da-7be637e65ad5"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("0d53d001-8689-4bc5-a310-a8085647d983"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("4cf843ea-ae54-433a-a5f0-6310828e8992"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("0b23f158-a04f-4eee-8c13-c19607ebda33"),
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("d0416c2b-5cc7-4b18-89b1-916addc99e15"),
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("a13d9a56-65f1-43f3-bb07-ec92d111d48b"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("3a7e7b83-b790-446e-923b-86383eb9419e"),
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = new Guid("7e44758b-24d9-44b7-9b3f-84a1b2779cee"),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("a41081fb-5b24-4fa3-b6f3-cc019ce7ab3a"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("36435a28-51a0-44da-93db-f0718a347902"),
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("54a6fb1b-2bf7-4595-a6ca-3a771ab5fca0"),
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("108e00e3-5bd9-4148-9118-99f7a6832fce"),
                            Name = "Democratic People’s Republic of Korea"
                        },
                        new
                        {
                            Id = new Guid("9ac7f4c6-a7de-4ab6-a8ee-5c46b6f7e484"),
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("a18b9e37-c154-4a2f-a6c2-df6491c717c4"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("331d002f-d8dd-4e63-ac2d-46f344630809"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("b1e55db0-1035-4340-b17a-7001115fd901"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("5b56b423-70a9-4653-b87c-2517514d2dc5"),
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("5b371fee-6760-4ca7-af8a-071ceae506c7"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("bcd1d840-da0a-4978-9daa-c3d5e1bac1cd"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("d47d42c4-b3d7-47fc-ae0f-369fa72cdb0e"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("f45c5b8e-eb5d-4abc-89c7-36f5a4f9197b"),
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("fa4cbe80-76c8-44da-a104-3a874785f210"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("828555ca-f09d-4732-8fa8-af7f49d15787"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("3f246f70-45e9-41e4-9256-7ed696dc8d76"),
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("e610b36b-b08b-4842-b469-5e0cebc70f0a"),
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("072f4092-3fe2-401a-8cb4-1491787223c7"),
                            Name = "Federated States of Micronesia"
                        },
                        new
                        {
                            Id = new Guid("248b1397-ec50-4189-9211-ed52365f4c61"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("df2c5cba-8e05-4562-bddc-5b78e5f07055"),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("60b60c04-6f1e-4cdf-a443-7c071d83ad71"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("3b6e4d44-c1e8-4394-a78e-a4350e409686"),
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("bc4e4c32-078f-4491-b779-802a759dda60"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("7cf219d1-43fa-4934-b36c-8ec5c25ff510"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("183ec8e4-9bcf-43d2-a53f-669c28b7f018"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("01345baa-ba53-4aa4-9b1e-3cd9fe0faf3c"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("0751fdfb-891f-4c3b-99a0-e66606022ef1"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("9dc18cc2-c460-4619-b946-feca04c660df"),
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("f87f06a8-f56c-42cf-b782-454a4202c92e"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("3a075aef-9b1a-4809-99db-bcf85e62aecd"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("aa24eda2-61c8-4665-ba8b-c39f7aa11053"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("0f0d4461-3c5b-4675-bdeb-f93bfed5e1d4"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("e7b66632-5172-40d8-915d-a74440cfd1ef"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("5eca9fc0-457b-4087-9ef1-5c9b0387b888"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("d0fdd057-4fb8-4520-87ee-f3bde4f117dd"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("695d92bf-b5d6-4079-ae95-fe072f409c56"),
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("3fc86950-bd71-4e26-85a4-97227ec39e19"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("4580f51e-96e2-4c83-89b1-9780a814bdca"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("e98c7932-0cf2-44d2-96aa-7b4199e2cbd5"),
                            Name = "Iran (Islamic Republic of)"
                        },
                        new
                        {
                            Id = new Guid("cd897b9c-8ecc-45b2-87ab-1515a650b088"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("4b27cb9e-642b-4c2c-a7f3-a76415589795"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("a6faa4a2-cf25-4dd9-87f1-fc3256ab5dac"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("b3fed1d5-5f6c-4538-97ed-9f9d96a80e0b"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("2671f0ad-a644-42ac-8f80-d237f34a0f00"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("f413b7a6-3277-4e9b-9be5-ee727b79c268"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("54876d93-7761-414e-8c3c-fea242d843a3"),
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("2d1040d2-394c-4411-a1f0-aeead11be915"),
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("f2d93871-0f06-43ef-872f-9aa046234838"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("95ab76de-ffed-4520-9f1a-e5e03ffbc380"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("e4b56a12-d6cb-4385-80e8-cc640eb92245"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("e13a77d8-309a-455b-9309-f6d7d895bc7e"),
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("cca5811b-e030-4ff8-b897-a4ccb7afe54b"),
                            Name = "Lao People’s Democratic Republic"
                        },
                        new
                        {
                            Id = new Guid("dd0b2966-a611-4d16-b806-2a8a3a1dfda8"),
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("b68d407c-4e8a-4159-ba62-a53cc54931e0"),
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("65607182-f9fb-40df-9f9e-2624f867716d"),
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("7d81dfb8-2b30-4fe3-81e6-3abfa4b0bb4e"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("2ff94163-ea5f-492c-bf7c-7a3ff47ce4c5"),
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("a3d5f828-5979-473f-80d3-7f85f0e6f676"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("423abc21-812c-487a-bb78-ca16eea171f4"),
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("f4e20545-ab4a-4bb0-994a-57a50ceab602"),
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("69040c84-4dac-4e72-9740-a15b49d869bd"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("3051d973-b17d-4291-a7c8-9672b533b3d5"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("4f31e994-1cb8-4747-acff-221c945b51da"),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("4135e63d-447b-4208-9b29-250ead9b3dc9"),
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("b6d997bd-c079-4a39-83c5-5dd9fa792aca"),
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("741679b9-ccd0-4b0b-bc37-d32d9a975ebc"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("2eedb731-b5a0-42bf-ad17-713bfc4f8358"),
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("7468a8f4-cdf8-47f5-b08f-9df60100b230"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("dc62deb8-afb0-45ab-bca3-17a279e14578"),
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("272c686d-1069-4b69-ab54-56207cea538e"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("d541a349-6257-4b85-a03e-9bffc0886bf2"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("f5495c61-6a94-445f-8696-03462c1ddc33"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("527af66e-ec44-4c23-afcd-c097dd05200d"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("242f3b26-04e5-47b1-9896-570881daf0f0"),
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("7fa5d82b-f213-45bd-85ed-4bf492c36917"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("b37fb6c4-070f-4090-8f0b-4808cf6c89a0"),
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("846274bd-eeb8-4863-90f5-b7f1548bbd8c"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("19e4e8ef-5811-45ab-8824-f404edc63cf1"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("ee30208d-1e36-47c8-8661-1c82f11ce6d2"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("7d370535-3cc4-48af-9a7b-8bc52601f028"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("8e4d3645-e4d4-4a53-9a9e-28b39e7420df"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("164ca10d-d39f-4c34-ae05-b88a25329a6f"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("a0c8b44a-9879-4424-8033-65bf0f05f813"),
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("9cb9477b-8c8a-4295-8726-d6f440759c01"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("1e554bbf-9986-4067-a8c3-3e02c928ac56"),
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("146fcce3-13bc-4fac-9d73-92811b2806e4"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("83e3eee7-7666-437b-880f-c27e2f712dc9"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("dd98a661-9938-4586-81a7-0c3db16ab440"),
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("33469ece-42e9-44ce-9e0b-b7a096510ac7"),
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("64e4842b-c86d-41d5-92dc-dda6562a38f1"),
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("34b0babb-a40d-4d57-adf0-eb2a1e8e64a4"),
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("92bc7766-ff48-445a-a110-6f81a001e5ce"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("b2e157e4-0ca7-4dd7-adc3-180f5017007c"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("4cbb974f-bf3a-404e-8668-04ddf7e977d7"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("7d82aab2-195b-4077-b89f-a61706461d97"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("0886ebca-1dfe-4b14-9584-8b218dd5f95e"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("e8548aa9-6baa-4e75-9223-605e44681c01"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("51beb08b-dc55-4bfb-ad77-fee7ad35dd51"),
                            Name = "Republic of Korea"
                        },
                        new
                        {
                            Id = new Guid("37dc7b3a-9aec-4dbd-87ac-5f46a0edf7f7"),
                            Name = "Republic of Moldova"
                        },
                        new
                        {
                            Id = new Guid("ed5ccb71-dee3-4cf6-8af1-016f2cc8162e"),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("30a4ff3e-44c3-4567-ad7f-0bde889c6696"),
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = new Guid("17d709f4-575d-4d8f-83bf-966f0c5aa79b"),
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("dc1902bc-e22e-4503-a782-7d45b802a2fe"),
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("65bf8beb-bc81-4c64-bf9c-b6b16a9e0614"),
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("42f1fb3d-7a53-4105-8b4d-38d35ba62cac"),
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("51ccda2c-585e-4b38-be0d-bea4d1f8ffa7"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("7c574a6f-b9c4-43f8-81d2-50d862de1692"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("4ae06e80-58e8-41f0-9617-6a26f847beee"),
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("b8c726e9-9950-4d29-98fa-9cc12271b0f7"),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("380a8ec1-4964-4e07-9f05-9139ba88134d"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("7ea5d983-aca4-4e00-862d-015ea93745a9"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("6382a99c-f2c8-450e-ad94-24e8834ffa83"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("984e536c-bab3-4e72-83e0-be17b8dea513"),
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("67806695-abd7-4747-a331-5031e36e38de"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("d7971697-0acb-45e7-b446-ad1530dc3fb1"),
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("1e25a8b7-6a27-4fbf-b09e-0ee0563f6471"),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("4152c298-b6c9-4833-80bf-0fd1416798f3"),
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("35afe216-2e3b-41f2-8482-997976a4e2f2"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("a4a8f44f-be27-4c52-98d0-218b0d49d535"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("773a6cf2-d0c2-4ce5-9caa-87c049b14fe2"),
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("6bb5e099-bcd8-4660-ae05-9c25a99d3b48"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("d6ae85d2-ea74-45d7-90b3-84c707a75cf2"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("f26ce06a-0c47-49aa-89f5-4892f33ba8ed"),
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("4f5318be-8fc4-4c41-96d1-852904790465"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("b633817f-43b6-4e2c-bfc3-49ed021206f8"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("0b5ba968-88d3-44a7-b3c7-ceb16211abe1"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("720b1811-5c47-4205-acc7-9b594a5fa498"),
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = new Guid("52923094-0faf-4c04-b29e-a8ef6f388f1a"),
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("5c37caee-64e7-4b20-ae3c-58ce6d9386f9"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("b7a66146-7147-45da-9549-01293728676d"),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("b4f63aad-5ee8-4c9e-be3b-8a4dbfb70b84"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("d22efef5-9d9a-4f5a-aba8-412065e0cea1"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("9a202949-6f50-4a67-92dc-b0cf218f5c04"),
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("41a83c28-d9de-4cf0-892a-4ca0fa7bdb3a"),
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("c371d51b-14a7-4952-97fe-d085acf97a2d"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("e01d9fe7-4f4b-49d5-9596-d16120a2ae20"),
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("3db966cb-3b9d-4da7-8533-80b34eff3ba1"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("c3c61312-4382-4fbf-8fc9-58d246dcb19a"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("a126e885-575b-49c2-b19c-6dfed4d067ca"),
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("2e27e741-9fd1-4642-a45b-8bc03f720b80"),
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("73937817-7bf5-45ee-a5e8-60cbb57af29f"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("1f7ef39e-5201-4d36-b082-f8397231e1e7"),
                            Name = "United Republic of Tanzania"
                        },
                        new
                        {
                            Id = new Guid("bca1e2da-9bb0-46a5-8e87-df6d6591f759"),
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = new Guid("bf0ed968-576b-4efe-a9df-aec87769ebb5"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("df1874cd-d230-4441-9300-b71c0fbd6c12"),
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("c29ae135-58df-4cb4-a158-1be36a0d2dc4"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("c7ed6af4-a043-4694-b959-db3855a828d7"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("a740ce0f-ded2-4272-8898-182a40f9f8a9"),
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = new Guid("b420816e-64e2-408f-983b-840993168739"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("2dc1bd53-cc27-498b-9605-8d424bf7282b"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("cc149a8c-10c3-42aa-a578-438f522d7807"),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("StudyBuddy.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("StudyBuddy.Models.JobRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobRecommendations");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpertiseField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentorship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenteeId");

                    b.HasIndex("MentorId");

                    b.ToTable("Mentorships");
                });

            modelBuilder.Entity("StudyBuddy.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StudyBuddy.Models.StudyField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyFields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8dff463-0048-40e1-907c-37d531228f7e"),
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = new Guid("7324a010-bcb8-445f-8b08-6610d3bfb980"),
                            Name = "Electrical Engineering"
                        },
                        new
                        {
                            Id = new Guid("85396aa4-d336-4b71-8343-48a428890777"),
                            Name = "Business Administration"
                        },
                        new
                        {
                            Id = new Guid("949248b6-6e28-487f-941d-e8a605269558"),
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = new Guid("935472ff-9f3b-4215-93bb-e11e4ba9cc28"),
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("37a244fc-21fb-49dd-bbcb-b302ece819f4"),
                            Name = "Law"
                        },
                        new
                        {
                            Id = new Guid("f08af45b-68f3-4865-87f0-8fdeb79d5e33"),
                            Name = "Biology"
                        },
                        new
                        {
                            Id = new Guid("7d49f256-4f6e-4a3a-ade7-d821c621fd62"),
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = new Guid("e0e4ce19-772c-4b5d-bdbb-41c244de126d"),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("357c8baf-d024-439c-9e6a-f46d820f12f0"),
                            Name = "Economics"
                        },
                        new
                        {
                            Id = new Guid("c4108cd9-bab6-4e04-994d-047b1ab7a2be"),
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("3a7ef5be-231a-45a8-b53c-d410a3f62aa2"),
                            Name = "Mechanical Engineering"
                        },
                        new
                        {
                            Id = new Guid("c0fd45b2-10a3-489c-a7f8-c9d1af562fbd"),
                            Name = "Civil Engineering"
                        },
                        new
                        {
                            Id = new Guid("c6eea5d4-6445-4824-87ea-f480666f075e"),
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("5fa83811-f94e-418f-991c-66a1f2219d30"),
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = new Guid("423c9ae2-653f-4790-8e85-a72ac120261f"),
                            Name = "Nursing"
                        },
                        new
                        {
                            Id = new Guid("424f65cb-dedb-4a35-a680-1bc3e504a116"),
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = new Guid("6d551124-461e-4137-b2d8-e91bd2f961d5"),
                            Name = "Veterinary Medicine"
                        },
                        new
                        {
                            Id = new Guid("192a70e7-f242-42d4-b101-b467fac657ed"),
                            Name = "Environmental Science"
                        },
                        new
                        {
                            Id = new Guid("48f94420-27ec-4a4f-9b1c-8c55302eb43d"),
                            Name = "Sociology"
                        },
                        new
                        {
                            Id = new Guid("79aec1ec-814b-4d8d-bbe6-8318d958e5c2"),
                            Name = "Anthropology"
                        },
                        new
                        {
                            Id = new Guid("2061a4b6-5ac9-45d5-bf53-461f39b30c54"),
                            Name = "Political Science"
                        },
                        new
                        {
                            Id = new Guid("64ae4157-f38e-4af5-9217-c823c4166119"),
                            Name = "International Relations"
                        },
                        new
                        {
                            Id = new Guid("ebb81e07-eeea-41a7-ac60-04bd8dcc52ff"),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("fffc33ee-1dc8-42e4-a726-2ae0a3320fc8"),
                            Name = "Special Education"
                        },
                        new
                        {
                            Id = new Guid("aa861d34-6f58-4085-9134-20c2b410f044"),
                            Name = "Linguistics"
                        },
                        new
                        {
                            Id = new Guid("844a2c6e-f1ed-47ce-a0f1-7d39d3174d33"),
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = new Guid("978a61f3-3056-48a6-b91f-a0eed05e13de"),
                            Name = "Theology"
                        },
                        new
                        {
                            Id = new Guid("47d4f6dd-a84d-4a62-a236-9e494459cd5f"),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("589c84ec-137c-4b56-9baa-094dd1829391"),
                            Name = "Art History"
                        },
                        new
                        {
                            Id = new Guid("e6aef2b3-472c-45a8-9a72-ce5087b15f78"),
                            Name = "Visual Arts"
                        },
                        new
                        {
                            Id = new Guid("c0732bd9-50ec-43db-8127-3b2a070584d6"),
                            Name = "Film Studies"
                        },
                        new
                        {
                            Id = new Guid("3bcdbd3e-246c-471c-9653-5b4c773cd380"),
                            Name = "Theater"
                        },
                        new
                        {
                            Id = new Guid("9591d56d-997e-4d16-ae61-5252894f4719"),
                            Name = "Communication"
                        },
                        new
                        {
                            Id = new Guid("0415f80b-c09f-4aee-8a66-e8410d8de8c4"),
                            Name = "Journalism"
                        },
                        new
                        {
                            Id = new Guid("33a99f94-ea47-4a09-8a2f-53cff3253223"),
                            Name = "Public Relations"
                        },
                        new
                        {
                            Id = new Guid("799d7789-a008-45e4-b155-17bd2693adf0"),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("f812f21c-fb81-4bd8-850e-0d2f422341d9"),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("fb1dd4f8-1634-46d0-89e8-e25f2dbc6225"),
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("6896efa3-a17f-4f56-96e7-ba54e7fd3f95"),
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("5753f39d-cbe3-467a-997f-7e2282d0a067"),
                            Name = "Supply Chain Management"
                        },
                        new
                        {
                            Id = new Guid("7f116ef4-7022-4e2a-b12c-7d941ebce2dd"),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("2a5dee30-f8c1-4cde-9b25-83c2ab54bef0"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("3efd8143-6cbd-4e89-b132-002201ccbd4a"),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("f598d008-ae05-465b-b547-c55c56af82d7"),
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = new Guid("a468b47f-4131-4574-b7b1-52840b188262"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("6a308361-17a4-40a5-9bb0-76af427d471b"),
                            Name = "DevOps Engineering"
                        },
                        new
                        {
                            Id = new Guid("59ea1bd7-8ae9-42e7-b1a1-1def2e684280"),
                            Name = "Fullstack Development"
                        },
                        new
                        {
                            Id = new Guid("33cd0579-2b73-466f-8ffe-01bdd0aa458c"),
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("a422697f-286c-42a9-9a7a-8801956a1857"),
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("7eab9d88-b83a-40f2-9580-5589f2216bfe"),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("ec5c29f0-cd49-4097-ac2e-a0e2639141bf"),
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = new Guid("cbcfe2a2-b0b2-4d86-af4d-e1fb993bdc51"),
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("354df83e-7055-4ee2-846f-a4c0139e5943"),
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("0b283a4e-7a6e-4a12-8677-157ee0a9751c"),
                            Name = "Animation and Multimedia"
                        },
                        new
                        {
                            Id = new Guid("3ac1fff8-dba8-4952-9257-214a8aa0593d"),
                            Name = "Interior Design"
                        },
                        new
                        {
                            Id = new Guid("9fed0571-3107-4a47-a3b0-11f56eb1307e"),
                            Name = "Fashion Design"
                        },
                        new
                        {
                            Id = new Guid("b3d020ad-2615-42fd-9831-e6aff03d2f60"),
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("7596cb70-ef42-4436-bbf3-146b701f7c87"),
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("5f00b305-5c07-4616-95ee-c732c6ca09fa"),
                            Name = "E-commerce"
                        },
                        new
                        {
                            Id = new Guid("0433c578-549c-4d5e-b2da-e75e596d9ab7"),
                            Name = "Business Intelligence"
                        },
                        new
                        {
                            Id = new Guid("72582eff-df33-448a-a5c8-360aee0245da"),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("3f38e533-9983-44d6-b41e-d1d82d82ad75"),
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyField")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50cfdd56-a69b-4c0f-b544-00edc799231f"),
                            City = "Tel Aviv",
                            Country = "Israel",
                            CreatedAt = new DateTime(2025, 5, 2, 15, 7, 56, 374, DateTimeKind.Utc).AddTicks(6451),
                            Email = "admin1@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "One",
                            Location = "Israel",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("390665a9-6c9a-4c0d-a59f-3e2d3b368a76"),
                            City = "New York",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 5, 2, 15, 7, 56, 380, DateTimeKind.Utc).AddTicks(4148),
                            Email = "admin2@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "Two",
                            Location = "USA",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("61175547-21bc-4e5d-a907-01a29b0d1cb9"),
                            City = "London",
                            Country = "UK",
                            CreatedAt = new DateTime(2025, 5, 2, 15, 7, 56, 380, DateTimeKind.Utc).AddTicks(4669),
                            Email = "admin3@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "Three",
                            Location = "UK",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("LeaderboardEntry", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Like", b =>
                {
                    b.HasOne("Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Activity", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.ChatMessage", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StudyBuddy.Models.Comment", b =>
                {
                    b.HasOne("Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.HasOne("StudyBuddy.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.StudyField", "StudyField")
                        .WithMany()
                        .HasForeignKey("StudyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("StudyBuddy.Models.Friendship", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentor", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentorship", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Mentee")
                        .WithMany()
                        .HasForeignKey("MenteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("StudyBuddy.Models.Notification", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.HasOne("StudyBuddy.Models.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Friends");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
