// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyBuddy.Data;

#nullable disable

namespace StudyBuddyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250503142345_AddEmailPasswordToUser")]
    partial class AddEmailPasswordToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("StudyBuddy.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("StudyBuddy.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StudyBuddy.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudyFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StudyFieldId");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("StudyBuddy.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6512784-f8bd-4ec6-aa07-97a8e08c837a"),
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("ea8e364c-a193-48a9-af84-e6c41a0913c4"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("8a37e7aa-feaf-4090-949f-63aeafd67192"),
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("15c6fb24-2684-4f60-bc33-d2f1d41b42d5"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("c3c5d486-2c19-4ef6-b4d5-9d8a05963ba4"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("ba6d36bb-2c8a-499a-b850-0bd90966b0bc"),
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("f577e1c2-c85d-4ffe-907b-1ac824809e0f"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("20638166-1419-40a2-bf88-368e15c0badb"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("89a509bf-110b-46fe-b814-77aa57828ba9"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("9d2f9c81-d7ff-49c6-a7eb-2489dc66f0e7"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("767d0adc-5e73-436f-af77-62e5206c6b73"),
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("d15a2d21-ed39-4a9c-8ed2-5621fcd166cd"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("6708579e-651b-4b6f-a87f-aac9c13539af"),
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("5c74debc-25fd-4a41-a5c5-2fda9553d3ee"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("25cca9d8-e76d-4c6e-80a5-762a2e08d8e6"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("f9c4b9c8-589d-40d0-9cba-3a9920c57e17"),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("c7943c1a-bd5f-469d-a509-dc2e7a2ecc88"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("ff86b003-8b8e-46c6-a078-ad1ed263d1c3"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("0865a6c6-51ff-49cf-aff4-09f1f641e07e"),
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("6ece6e95-9c7d-400e-baeb-8dbb181a1e19"),
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("c7bae37b-c15e-48d6-a019-f22673b48370"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("7ebd1f27-a052-4629-9432-e4caf4198b7b"),
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("c6584382-3733-4b22-ba5b-e433e7b85685"),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("5fb1d3c2-bbbc-442a-b90a-847e7b0aa192"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("b521fb62-7265-4d43-a014-daf0e3444436"),
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = new Guid("5fbafd93-2a09-4fca-9f55-07bcb14152ad"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("a571624d-453c-45db-a011-ab5b53ca96c7"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("3b209592-bbd3-445a-8fc4-ee507fa1fe04"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("d659e744-9ef7-4b76-9d9d-997a6f07c7c5"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("b2d3c7b0-8035-4ea7-8c87-bf15b00a6568"),
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("879fc656-5747-4d14-a422-2107bcbfb6a0"),
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("ede0dbe0-7e8e-4343-a76d-52b6de4ff191"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("8212b670-9fb4-499e-a4f0-f7f175ba8676"),
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("2c815689-d213-4653-a549-1ada98daa40e"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("80953555-8971-4f10-8ea1-9f05e32d05d4"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("1a31705e-c513-4730-9fb6-87486f498935"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("e61b9167-5a5d-4ad6-afcc-a958ce42adac"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("3481464c-46ff-4f25-b6fb-cf3fd71bb7ee"),
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("dcb321dd-4eb9-46b4-a858-5c30d136b216"),
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("359e8700-7d19-47a1-802d-f408fc0adfe9"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("efa5883e-bb0b-424c-ab3c-851f0d830523"),
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = new Guid("20c63948-0534-4e2e-8ee8-f11c3273aafe"),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("6fef24b8-6f59-48ae-9f32-5c85daec66b2"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("763d7c36-820c-4ef3-99d1-5571ec16a99b"),
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("1afc6161-706b-4b82-9005-f7e791b57144"),
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("87344ea7-6564-430a-86b5-60d74b228231"),
                            Name = "Democratic People’s Republic of Korea"
                        },
                        new
                        {
                            Id = new Guid("221f3c69-023e-4e0e-9007-d3f17d7adf51"),
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("30d93526-8c51-4316-b0de-7f30abac01ef"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("1ee1d4a1-f256-4b2d-a3ac-c70ed7b65f1f"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("64a5c17e-8a5f-4987-a15c-0337d5e16baa"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("37e872b7-cc8e-4ef9-a54b-de90ca70fcb6"),
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("3de26b80-241e-4159-81ca-3a4f358d30c7"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("9b926b14-2c76-4926-a7d2-6f91e81122d6"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("c07da7e5-d83a-49ef-8087-d7a1c10237c2"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("f4554fbc-5d8e-473a-81a0-7f3aea7b04bb"),
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("d64dc6a1-2eca-4f7f-b5c1-f77b850ebe94"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("405795c4-5ba8-43e6-99be-aedb153ada56"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("2442368f-67e4-4b7e-8704-169dc2632c25"),
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("85df3099-dac8-437e-8b17-a7c2cff39364"),
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("9f374410-f44e-4847-a796-d386545053f5"),
                            Name = "Federated States of Micronesia"
                        },
                        new
                        {
                            Id = new Guid("ce790418-de15-4d7e-a754-07fca2aecdff"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("b934b198-79d9-445b-a9b7-bb8db62e38a2"),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("02da320d-bfd5-487e-bc48-edb870cc420e"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("936ead80-17d1-4ed0-8382-514dd4dc7696"),
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("0d3d90d5-86b8-4a6f-a10f-38fe0f23d47a"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("1a7c629e-3bd3-4f84-ad6b-0fd33b9760e8"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("59a962e4-c655-40fb-9982-300f228c9c8d"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("d48f7d87-696c-46cc-8868-e71ed9f8618f"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("02c27073-a83a-4a1e-8ae5-dfd0f8563a8d"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("82c44a64-7838-4c2b-a673-bf6a08729eb8"),
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("763fb15a-970a-4b76-807c-cfa44438884c"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("5fff9e97-498b-42a7-bb7c-1be3463f5d44"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("b855bc3e-3574-471a-a2b9-101d8f3fc91f"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("0d4b6fd6-5ae7-4baa-a4d6-e12aa0503efb"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("a923d462-d423-4e29-a394-aad88bfdc43a"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("b130465c-7633-4206-a049-190886673c27"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("5d360dc8-f3f8-4f17-a174-bc1453b3304a"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("20481f14-68ad-41f4-9a41-a9b28889d223"),
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("93376b5a-eae1-4bd3-9cac-6e3159440d85"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("f60e4d99-6e2f-4c88-a160-2cc63b36ca0a"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("08e4ee4f-aa0c-4160-9c7d-ceba3e408fe0"),
                            Name = "Iran (Islamic Republic of)"
                        },
                        new
                        {
                            Id = new Guid("958c6524-e557-4307-9581-275a066e41aa"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("292b5a45-6186-4edd-b9f8-c1bc776ccd1d"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("ccfdf511-34fc-417b-b338-51a76153234f"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("298149fa-1b79-4974-9f0d-fbaf2e20de83"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("99a82519-b1a6-431c-a400-80b2af8a6e1f"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("9da58c99-7a60-405d-86d0-0ee57977eec7"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("bf1fecb1-daea-47c0-9a31-4e7ba87e3b8f"),
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("9289511b-22ae-4e9b-9b38-fb1019ba1fa6"),
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("4e04532a-77e7-4f90-8aed-679a714f7070"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("111898b2-3aaa-4268-bfe4-7969f283d4bc"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("d804ed1c-b725-4ae6-a29c-e111294255d0"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("aec7c6fc-eda5-4bf0-befc-da1cd076c159"),
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("f80faaa8-8012-4a34-819f-cbcd69bfb427"),
                            Name = "Lao People’s Democratic Republic"
                        },
                        new
                        {
                            Id = new Guid("246605d5-174b-46c8-8124-53b271f5c03a"),
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("f550e29d-e8c2-43e3-b900-10bc19fcee50"),
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("04f68471-1b22-4012-b759-bba4715592a6"),
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("0ad27e9e-c5f3-49e0-8197-09cf65fd37fa"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("737f8ca5-6c0b-4745-9d30-4a64f6ca3b3b"),
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("55e88e73-1303-4256-91ac-9c53b2bffa31"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("35d361de-a82a-4bdc-8cd6-9ae30fedb921"),
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("72d06884-81c0-451a-a74d-a812e7499dca"),
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("ed624080-56f7-4533-9c15-adb9feae4f0d"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("b26424b7-67f4-4c68-a0db-060175c110ea"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("f1ca1e71-a080-43c5-b571-c73f86d9e97a"),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("22fc1b2b-e19d-4022-b43e-3c42398970c3"),
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("f19701cb-a319-46a7-9f53-ea36829e84a0"),
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("522a1072-5543-4543-9462-4d9534b93edf"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("0454dd99-2206-4e90-98b5-225f91f97300"),
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("c7dccee1-1ee7-4928-ab2a-bbe3ac51327b"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("91a63a49-9a69-4675-b6cf-3c3843ef46ab"),
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("3ec088fd-c6e1-4746-9b79-68e601f9d84f"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("4917f085-e3b6-4943-8169-9430a0a6d01e"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("81f5500a-f6f0-4d26-8a86-fcfa4f663170"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("925cfa44-9322-4c43-9511-e045fceb6b7d"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("dc031d7f-0981-418a-9a7a-b9459153bd88"),
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("96a446fb-2cfe-4852-9f25-b8f180ae7fcb"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("89fc1866-1bf8-44ef-bddf-704badf91530"),
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("7988ed95-3499-42c8-9eb7-57e28455a6b0"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("6148d21f-209a-4ba4-b9ce-f8467973e8f8"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("de1fc034-9a2f-4729-860e-30834957b610"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("339e6f4b-54d7-4f71-8677-b8f0f7d01d40"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("45b5486c-7341-46f1-81d8-0bfff3eb55e8"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("6afdc26f-0a1e-4a13-8ea9-fd5db7975952"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("49cd3429-ee3c-4d02-9262-04f8a4059782"),
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("63f6bf6f-3a8a-4418-928b-bf69fa1d5961"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("efc81a4a-662e-4799-8623-3c3e3c4f6eda"),
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("63804032-ad5e-4876-8ed5-8ac87ec534b8"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("70f32a33-b7a8-49c8-beec-02535c9cf521"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("c8a643e9-66e6-4148-bb29-49727976dc05"),
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("ac93353c-aedd-4cd9-9265-d57367dcb473"),
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("451a0559-1e6c-41df-ab68-5bbeb74cc1c1"),
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("ffbaf164-eee5-4036-8e54-bceeed9e10cf"),
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("f055930e-0385-4f51-acaf-867fec21f9c4"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("d0b0285b-99b6-4b8a-aa65-7df6abaed306"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("4737cb89-a840-4223-b24f-4de46427d1e4"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("fbea90a2-ffc9-4288-bb9d-dac171a332ca"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("46b4a1f2-c28f-41fa-8228-4e67df403f40"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("89783845-c6e5-488c-bb9a-f52ad360ec5e"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("5208e37a-6e8c-46bf-aae3-4cd21c94039c"),
                            Name = "Republic of Korea"
                        },
                        new
                        {
                            Id = new Guid("de176fe1-cc5c-4984-a1ca-05a923825e5a"),
                            Name = "Republic of Moldova"
                        },
                        new
                        {
                            Id = new Guid("cabb3e02-eede-4991-9057-ab0d8a0b79a0"),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("5ee1ce1c-0248-4535-80ae-264008bee994"),
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = new Guid("cb75d2e9-d793-464c-ab41-f135e2989b0d"),
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("43ed6e4d-d23a-4325-8640-266609b2d690"),
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("3e53eab3-d2c0-413f-a86b-08c4fb8b7ff1"),
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("d9f051dc-86c5-4150-8e2a-eb3179f8f7cf"),
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("bac8298c-f332-4312-8160-6d247b2440fe"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("d06b83a6-69f2-4844-a914-96d3c90dcc37"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("9b21a88d-7bf6-4af9-9462-9d153d40333d"),
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("9f006d53-b33b-439f-8189-5f8a97dba81b"),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("c9122bec-144f-415e-9bff-3176671af921"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("6c325dd6-66d1-46aa-9322-df65e3c2b898"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("83e01d5e-1c4a-4154-ba48-951765f8f17f"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("51ce7a95-64da-45f7-b3ef-2ed6953a5703"),
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("76cf5534-22b5-42e1-ade0-b61c2b232526"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("def41c5e-cef0-4f44-8464-fee728ee988f"),
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("4a904a1c-e34b-4e72-a336-42d4d4c8c669"),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("7439bfac-1d61-4dca-8dfe-787c159ae536"),
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("1336df21-c69f-41f8-901a-4ca027d773e4"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("2c2d9fc4-85e1-4f63-aca5-a35243f95a4c"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("08bad423-b9db-4115-a830-39ed398973c2"),
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("b72e2c1c-bf60-4f16-abe7-60e18338a900"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("66f4335a-2979-4598-b871-7791c6b2b383"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("26544ad9-3ee5-46a8-9908-4f35754647ed"),
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("591dd074-e4cd-4df0-b4b0-59582ccf6948"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("fdcd76a8-071c-40bc-aa26-bdf11b1ba67b"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("8b526a1c-c0af-4eec-a644-7ad33c6adee9"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("10f7eec9-296e-482a-ab68-e290c29b51d4"),
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = new Guid("1fda00b2-f2a7-406c-bc65-c1a2720e0fde"),
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("c81e51e5-8122-457c-af52-a75bdf93d671"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("8c33eafd-d4f7-43aa-9d1d-303bde2bdcbd"),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("553f96f6-febe-4dbf-ad54-44d630235051"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("6607d312-42dd-4f8d-ad7a-8e06c2361c8a"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("8ac7a2b5-2216-413f-aaf2-a27830d35c33"),
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("3d057b0c-bec8-4f43-8f89-649ff17a0c40"),
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("afd9301c-3783-4daa-9179-93314a5ca3db"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("8dfa1454-5721-4957-b207-e61c2d441649"),
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("f8f66c1c-8450-4ea9-9862-242bf28d59d1"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("4acc4eb8-518d-4df9-b0b1-3e32b33e2170"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("1ac63b6b-7d4d-43ec-b67b-033ce0a24bd6"),
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("bd9f8561-fb76-4823-bebb-247211f95d3d"),
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("b15181e5-9ca3-453a-b0d2-51aa9b903ec5"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("c3d70cbb-b421-4e84-9996-d121b5cdf40c"),
                            Name = "United Republic of Tanzania"
                        },
                        new
                        {
                            Id = new Guid("f4cde409-dc29-4d6d-befa-176534adb934"),
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = new Guid("5d297cfe-4188-4b21-8411-7e4dc156f650"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("55e6c82a-24d2-4009-b2e8-d3295dd098db"),
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("6aac487f-fead-48b9-9099-abf315c5d15c"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("141f6ddf-1878-4d78-8a05-d64dea52687b"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("43fdd93b-41e9-43a3-baf8-b8057c7ebe33"),
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = new Guid("4520e66b-93db-4d26-94dd-8da20120bfd8"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("7a854bdd-c0a0-4f33-99c0-136a744f7b5b"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("eb6f04c5-1d89-419b-b0e6-00a0445556b3"),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("StudyBuddy.Models.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("StudyBuddy.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("StudyBuddy.Models.JobRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobRecommendations");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpertiseField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentorship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenteeId");

                    b.HasIndex("MentorId");

                    b.ToTable("Mentorships");
                });

            modelBuilder.Entity("StudyBuddy.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StudyBuddy.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("StudyBuddy.Models.StudyField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyFields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2f9439a-6ad3-41b6-9d8a-66b25de6039c"),
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = new Guid("a2c93008-1efa-4d7d-b849-c2fe23cd7cd9"),
                            Name = "Electrical Engineering"
                        },
                        new
                        {
                            Id = new Guid("638a62d5-75b0-49e3-9851-f20c9f49b083"),
                            Name = "Business Administration"
                        },
                        new
                        {
                            Id = new Guid("a26e2961-a7b1-4f33-af63-d84a86bffea3"),
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = new Guid("374239ac-586b-4ef4-8960-efe7b1ef8b08"),
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("c2608c60-cf75-4b94-b472-0bdcb10c0305"),
                            Name = "Law"
                        },
                        new
                        {
                            Id = new Guid("d7ee1a7b-a437-4ce8-925d-8549f24cb908"),
                            Name = "Biology"
                        },
                        new
                        {
                            Id = new Guid("cfd38d81-1738-48b8-913a-fd72d2b856bb"),
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = new Guid("087509e1-ae96-4fcc-92ad-867bd7ba7c87"),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("227c7578-16b8-4a0e-88f6-813505ed0c35"),
                            Name = "Economics"
                        },
                        new
                        {
                            Id = new Guid("d83ec927-4efc-47df-a431-dcbc6fe6c620"),
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("367a7d1f-38c3-4861-a6ed-c952a5199ef1"),
                            Name = "Mechanical Engineering"
                        },
                        new
                        {
                            Id = new Guid("299d4710-2037-4c21-a435-6e95beb40834"),
                            Name = "Civil Engineering"
                        },
                        new
                        {
                            Id = new Guid("0f8e3549-1cde-4fcd-bf2a-8af277256798"),
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("91751257-539f-450c-a0eb-3d79d035df4e"),
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = new Guid("112553e0-9446-42f3-b986-e59e50f749b3"),
                            Name = "Nursing"
                        },
                        new
                        {
                            Id = new Guid("f62e324c-a800-4e38-8b3e-28327f0ac9f8"),
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = new Guid("fe524395-0203-4c46-8498-8b14de36cc3b"),
                            Name = "Veterinary Medicine"
                        },
                        new
                        {
                            Id = new Guid("4ba8d26b-ea38-4110-a7bb-cec361162704"),
                            Name = "Environmental Science"
                        },
                        new
                        {
                            Id = new Guid("12664761-c91c-4a25-9622-9c07a1b644f0"),
                            Name = "Sociology"
                        },
                        new
                        {
                            Id = new Guid("91295781-ddf7-47d2-95fb-75bd69e9b1af"),
                            Name = "Anthropology"
                        },
                        new
                        {
                            Id = new Guid("29d47cf0-5ba8-466a-b65a-8d3033d57cf9"),
                            Name = "Political Science"
                        },
                        new
                        {
                            Id = new Guid("97bf5ad4-c61c-497c-98f0-14ae61306d76"),
                            Name = "International Relations"
                        },
                        new
                        {
                            Id = new Guid("54960527-aa39-4ae1-8c7c-dd71bd26dd9a"),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("5321d575-8553-46fe-b66c-c265c35e0d55"),
                            Name = "Special Education"
                        },
                        new
                        {
                            Id = new Guid("d79bc758-fcd8-46e7-bb8a-0c5330a5ae7c"),
                            Name = "Linguistics"
                        },
                        new
                        {
                            Id = new Guid("01caacbc-2020-4143-a580-f53a22cbc4c6"),
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = new Guid("7c3a9ce7-e6cb-4855-ba74-4d76a9da0fcb"),
                            Name = "Theology"
                        },
                        new
                        {
                            Id = new Guid("81932a0a-9f17-44fe-a6ae-3f34663b855e"),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("b7cc7ffb-4efc-41ee-880f-12a85fe86b28"),
                            Name = "Art History"
                        },
                        new
                        {
                            Id = new Guid("98709cc6-5c10-40ae-890d-a0bee4e6f30f"),
                            Name = "Visual Arts"
                        },
                        new
                        {
                            Id = new Guid("183d8c84-a332-4356-907e-efccdf686e02"),
                            Name = "Film Studies"
                        },
                        new
                        {
                            Id = new Guid("430db5c9-f5fe-46d0-b934-360f940f4d43"),
                            Name = "Theater"
                        },
                        new
                        {
                            Id = new Guid("58065f87-9a9c-40e6-8718-ae6d17355625"),
                            Name = "Communication"
                        },
                        new
                        {
                            Id = new Guid("f4b9a123-2527-4fc0-be47-3eb5d3cbe470"),
                            Name = "Journalism"
                        },
                        new
                        {
                            Id = new Guid("2caa1b6e-e70e-4727-b1b3-c4c3f1344d07"),
                            Name = "Public Relations"
                        },
                        new
                        {
                            Id = new Guid("3b9a8006-0ba3-47ff-b71b-e206d043da6d"),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("05c77e8a-61e5-4198-ad04-a8787f771da7"),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("7dad8bd4-891f-4f99-b27e-e9bde64fa002"),
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("9ab9dc78-4b22-4c33-95c2-96bc5fbbc665"),
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("731fa297-a0c5-47a6-9337-a938df8a8825"),
                            Name = "Supply Chain Management"
                        },
                        new
                        {
                            Id = new Guid("a3577ad3-46a6-4645-9c8b-6e8c912a9df2"),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("1e5d7666-c1db-44ab-aae9-5e3b6c7e6631"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("37f93db9-781b-4717-bf39-92263822c318"),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("f88412e4-6970-415c-a746-c7010325326f"),
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = new Guid("6711c543-f446-4a0f-b846-0636bf2d96fe"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("5e7f5ed6-ae52-4c7c-8e34-65ff3a454401"),
                            Name = "DevOps Engineering"
                        },
                        new
                        {
                            Id = new Guid("9c275769-a9f2-41ae-bf25-4e7a05125e63"),
                            Name = "Fullstack Development"
                        },
                        new
                        {
                            Id = new Guid("047366ea-fc96-4d77-b4c7-89587cc12a0e"),
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("ee475313-c274-4142-8384-2d2b529d95ad"),
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("b2958f64-fcd1-48e7-ad9b-82a8e85bea11"),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("1e764495-1675-497a-b622-e0271500b09b"),
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = new Guid("17a39e46-c86a-45ed-8b6b-3e695c8deabd"),
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("a1113cdb-2466-4047-9247-536990365b58"),
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("07ecf088-07b9-47b5-9b73-02f92f4419c9"),
                            Name = "Animation and Multimedia"
                        },
                        new
                        {
                            Id = new Guid("6d03f262-dfd5-4f4f-8fe7-37cad73ea000"),
                            Name = "Interior Design"
                        },
                        new
                        {
                            Id = new Guid("f8dc0f17-381f-4c9f-9280-75b126c17bea"),
                            Name = "Fashion Design"
                        },
                        new
                        {
                            Id = new Guid("80678138-1d50-4dbe-9c70-48321191b04c"),
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("7f009c3d-4875-4d3c-94a2-b22698cd26c7"),
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("0c04ecbf-b73d-4834-acb1-424624193f2d"),
                            Name = "E-commerce"
                        },
                        new
                        {
                            Id = new Guid("6ba2cb6d-4793-48ec-a84c-affb48381d44"),
                            Name = "Business Intelligence"
                        },
                        new
                        {
                            Id = new Guid("9d52fc60-fef9-4291-9e0b-d6bc587931d7"),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("8cb4d364-9736-4f84-b4df-23c3dcfadae0"),
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyField")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("321f783a-0ac5-462f-b1aa-bb589fec369a"),
                            City = "Tel Aviv",
                            Country = "Israel",
                            CreatedAt = new DateTime(2025, 5, 3, 14, 23, 44, 636, DateTimeKind.Utc).AddTicks(1015),
                            Email = "admin1@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "One",
                            Location = "Israel",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("3288ed3e-e1d9-43ed-88b6-8b456321bf9c"),
                            City = "New York",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 5, 3, 14, 23, 44, 640, DateTimeKind.Utc).AddTicks(9218),
                            Email = "admin2@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "Two",
                            Location = "USA",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("fd57cee6-0780-4a2b-a2bb-effa0a6d5822"),
                            City = "London",
                            Country = "UK",
                            CreatedAt = new DateTime(2025, 5, 3, 14, 23, 44, 640, DateTimeKind.Utc).AddTicks(9593),
                            Email = "admin3@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "Three",
                            Location = "UK",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("LeaderboardEntry", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Like", b =>
                {
                    b.HasOne("StudyBuddy.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Activity", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.ChatMessage", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StudyBuddy.Models.Comment", b =>
                {
                    b.HasOne("StudyBuddy.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.HasOne("StudyBuddy.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.StudyField", "StudyField")
                        .WithMany()
                        .HasForeignKey("StudyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("StudyBuddy.Models.FriendRequest", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("StudyBuddy.Models.Friendship", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentor", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentorship", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Mentee")
                        .WithMany()
                        .HasForeignKey("MenteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("StudyBuddy.Models.Notification", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Post", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.HasOne("StudyBuddy.Models.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("StudyBuddy.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Friends");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
