// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyBuddy.Data;

#nullable disable

namespace StudyBuddyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250503114204_AddImageUrlToPosts")]
    partial class AddImageUrlToPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("StudyBuddy.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("StudyBuddy.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StudyBuddy.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudyFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StudyFieldId");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("StudyBuddy.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56c9ca7c-7525-480e-b1c9-5cd94f2d4fc6"),
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("83b87941-d6a3-4fe6-86ed-21c37538e385"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("89e37c33-a631-43bf-819c-04762b8cb65a"),
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("8990e39c-77d4-414f-9f05-d54af86edc5e"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("06461b60-e133-46c0-95e3-24a4ea153eb6"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("5c194a23-3a0a-45c8-bfaa-2ee86f95326d"),
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("044af54a-44e7-446b-a242-d4ea761dd0e0"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("0450ce81-7498-4838-9287-d26dc638f858"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("6768bb10-8711-4e79-894c-20015ae0f69d"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("9c5c3218-a78e-4426-a6c3-953098875f6c"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("b63f4eca-bc69-49ec-8146-c4e624aff001"),
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("3322a3c5-2f22-4d88-b282-75665e0a8544"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("1965bc6f-fcf5-446d-83af-9c54baa2fc0b"),
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("466b0961-14d8-4ffc-b785-ddc73138726b"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("f9899eaf-1afd-480a-8ad4-7bfeab5de170"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("cbfc546d-bde5-4a26-9e65-1c0b11a22ff7"),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("28a6e37c-48a9-45a7-b0d3-9130d2f32679"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("1fdde76c-836d-448a-bf55-d399880e855d"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("89a6f3d3-97be-4ed6-830e-1d28d66bbd27"),
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("82fb402f-c38f-4c60-a9f1-249d3dd8bf8f"),
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("c78491ae-2775-4394-b53b-3444e4a6b4ff"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("f3919570-5932-4334-a8ad-180ac69c8425"),
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("0a79bdda-9519-42a7-945b-035bb59ab3af"),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("d42e9df2-4a39-416d-acce-6049f97c471f"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("eb52aec4-19ed-43d3-a372-108cd898e7af"),
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = new Guid("8ac800da-db16-4758-8473-ea6a9ffd3ba2"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("aa2b6293-156e-4eef-bb6e-2cd260816a4a"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("3d7adeeb-75a2-4cd8-9052-7d6aaca133e9"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("09a17d8b-d102-4f1f-bc87-8b3a9aeab7d9"),
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("4f5253cb-0464-4e0c-a367-3ec01c23275f"),
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("04a34ffa-6ceb-4a7c-8251-b697f0309587"),
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("cfafa131-81ba-424f-a101-ad277dabd800"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("e02c0faf-4617-4507-8ce0-035e77b0de5e"),
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("23dcbe27-804a-4f55-af73-32f02cf1a846"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("2df4fc85-0e78-42cf-8650-85e5d151e049"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("87c058d5-6a53-4a9f-b290-9ce2cb1d586c"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("c6633103-5b71-4bc7-a8f4-794f2ae112ba"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("f19c32b2-dfe7-48ab-8b2f-1891d904a6f1"),
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("6e47c362-79f5-4d45-9932-5a16bf080fc9"),
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("5d0f40f1-e803-4e0a-9d20-06dd6bc1cd99"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("b857fc15-ca04-43f8-8c6d-be25a40af2b7"),
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = new Guid("2299ddf4-d7f7-4a5e-8003-918c119a8b66"),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("71610e89-61c7-4aba-9153-c7598ee6c3e8"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("c4753a53-aa50-479d-a5c8-bec19528904b"),
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("a97c84bb-9bff-4ac7-97f5-b372a5f250b3"),
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("76986b2d-1e41-4ca6-971d-988f85ad43b1"),
                            Name = "Democratic People’s Republic of Korea"
                        },
                        new
                        {
                            Id = new Guid("085c246e-3e60-4ac0-9013-9cd4477ded4a"),
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("6203e0c1-1684-460a-9550-3dc70d0698f4"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("e10acd0f-7937-4113-934a-63bcd87f4826"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("25181e18-1f5f-4742-bbe7-4169d4b0f008"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("fb3559ce-c79b-477f-b122-4feb4e0d9b8c"),
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("44d4028e-7d1a-4ae1-88ca-1745f4176c48"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("05dc83a2-8cb4-4860-ab13-627985aab203"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("bc3ff26f-249f-499f-a17e-caaca39bf3f4"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("c8ed85ad-f4c0-43f2-a5a9-a7b5179183b0"),
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("56b44407-316f-41fc-9984-2a4fa76ff940"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("9cbea40d-704b-4fe8-b52f-02963954183d"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("dface041-1a14-4dd0-aeee-99469365df6b"),
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("df64650c-f1dc-4cd2-9318-66b2e5e3a201"),
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("68fa5066-a478-4cb8-b57f-5a7c841ec7a3"),
                            Name = "Federated States of Micronesia"
                        },
                        new
                        {
                            Id = new Guid("409c7a13-a0f3-46c9-89c8-79714b5cee27"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("db351e4e-a481-4d01-b574-97dfc0855666"),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("679a27bf-0303-4698-8f62-e0e9f7678203"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("30433e60-5b50-4bae-bcc9-0ee18f969e9d"),
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("7f09c413-c390-4aee-81b8-f74df13aabb7"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("373f9be5-09b9-421d-b1b0-31a93041bf79"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("de7d05ca-eb89-44df-875a-21e12eca9864"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("ca374fe2-9678-4696-b4c2-ea4330d87f1e"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("0ddd4002-d2a1-42a9-90b2-5d62282e3865"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("3305ccf0-2043-4987-a187-a974f1724baa"),
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("5a1e5dd8-bc20-4ae8-90de-d97ffec719a1"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("c8199013-e322-412f-9c87-8bde251930d1"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("9e7a7b86-2afb-4d36-8b12-c45641de7587"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("f87001f7-4641-420b-b301-73b1b0557b57"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("835dd983-27c4-42cf-b5de-0c56514cc5b3"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("eed68d60-8fd6-4707-9d48-e2d08dfb4f2e"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("ed9e2e13-89b9-4df9-bedb-c89e314595f5"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("b396b87a-922f-4092-8afe-208cbd7d9828"),
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("66f9487c-1018-4c46-876e-dcfac6dc020f"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("0e56141b-a647-4e6d-9356-b9e809f2820e"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("f3a0e686-ff53-4777-a0e3-16e8cf54926b"),
                            Name = "Iran (Islamic Republic of)"
                        },
                        new
                        {
                            Id = new Guid("665627a2-22fc-4815-a079-cfb3550156d7"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("fe9f971d-7635-4ec9-90ba-4fa979d1ebf7"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("505b6a98-de70-44ca-b910-a6cef62e5538"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("bce41870-abf4-42fd-bf01-db7c2cdda6f3"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("54e15cd1-a299-4e16-8bdf-1036a6202dc0"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("869e13b9-9553-4d4e-bd27-e26daf6eeda0"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("3af91145-f396-4e21-9d13-a85c2f0066e7"),
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("865fc5e1-0443-4878-8d62-8a22c9c9fe14"),
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("124544ae-2baf-4f49-adf8-5839f076bb22"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("df18530d-8352-46f7-8ec2-30b29dc40bb3"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("0afb7976-f94c-45ba-8ad0-e6483c0b3819"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("25688699-ffb0-4a27-8f79-a4fb0003a8fa"),
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("e9860d38-1563-4e8c-ab63-7fbc0fabf59a"),
                            Name = "Lao People’s Democratic Republic"
                        },
                        new
                        {
                            Id = new Guid("61053c1e-facc-419b-8999-0853eadf0467"),
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("c611756f-f676-4da5-a657-3658955c59c4"),
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("f73f7217-a25b-4809-b9f8-714ef805925b"),
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("1ecf184c-8d5f-4bb9-b589-61f12756ff6e"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("d004f9a9-6316-4382-92ac-8bd8fcd53c31"),
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("5f9d9d3d-7504-460a-a60a-1947a86263b3"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("c3708107-3d02-4c9b-9df8-c647bf7c41cb"),
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("e74eb3e7-d42e-4b91-a8cb-655ee9807347"),
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("1107cc67-bd7e-42d3-938f-b5e11b724173"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("8cdcd071-6783-44d1-875f-23f6745f1953"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("9dec491d-e6e2-4164-a4bc-01a57e75606c"),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("0d5636b5-1fc9-43d3-b67d-f142209d66d9"),
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("f8a2cf28-7c3c-47cf-8ecb-8bddd87d1537"),
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("29d3a1a2-7ddc-4a76-bfc9-0f95c5eed76d"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("07db0e2e-8820-4d2e-bb11-1a57ffb20d47"),
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("3319ba1c-ad19-4dba-a6ff-642b4ebbce51"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("17fa3e37-f582-43a3-90d1-b4d211ca5303"),
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("59bac0ba-b87a-4c34-be14-998e2e2ce914"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("458b195d-8ba9-49da-afc7-c8b24670d79a"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("6fa6b907-2892-40f8-ba94-9ebadc078a2c"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("cf12c654-6a13-4db7-9411-63b4455a3819"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("be8a2b9b-1031-4a4a-8e45-2c88f08292f1"),
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("d613bcd7-7d40-4025-854d-978026a97f90"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("d17f76c5-2ff5-4816-8f86-935616155602"),
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("6734af56-2390-4771-9e11-13b788e6618b"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("377dfd8f-2582-4413-b8d6-89826e6f64f0"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("607ef286-bfd7-4480-b914-ed9c147e1f7e"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("6ff3b6ef-07ea-406c-9cfe-d7f89fd98438"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("6d7e6409-bb25-434f-ab9a-b2079855e4d3"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("db84508a-c6fd-4d79-a726-b1805765a5cb"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("7ccf3a0c-027c-45b9-826f-ccb72298b2cb"),
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("e17a85c8-914c-444b-b249-be6b3172c254"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("ecf99fb9-4f48-42d4-89b2-ea657043c706"),
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("3ee9ed0c-7ee3-4bb8-9d6f-5743d0326172"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("b13c0d97-d3b8-4740-8051-4d214092f347"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("a1003654-8de8-4d99-9705-a45d6900f60f"),
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("6765611c-e89d-4c98-af29-2f33a881120f"),
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("ca747f00-307a-4548-8927-4e9466d95566"),
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("bba22f96-e1f7-4044-b72e-e1a2632521dc"),
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("4658cd17-74e6-4e1d-b3ca-67c49c000e28"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("54bbe55d-aa6c-4c0c-8dcd-6cd235968173"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("53205184-1e5b-46a8-a4a5-2fea5a7e3ba0"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("69a34485-f218-44af-956c-034cec3bbeb6"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("08cffc33-6f5a-47d6-bca7-949374a14fd6"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("56c9e36a-39f5-4c58-9e4f-3e88c1bb5b24"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("3adb2f5d-13c3-4ecc-b49d-67baa1c4667f"),
                            Name = "Republic of Korea"
                        },
                        new
                        {
                            Id = new Guid("31341c81-5e55-4501-9f97-98c09c42364e"),
                            Name = "Republic of Moldova"
                        },
                        new
                        {
                            Id = new Guid("d344019a-e763-423a-a109-08723aae711f"),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("cf274b13-5335-438e-ad2d-ce000eea6d09"),
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = new Guid("96b7d40e-fa42-443c-83e7-ecdc08d6752e"),
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("3f248819-dda6-4525-8e54-b5e0ca3ed84b"),
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("f019ac6d-ac16-4343-8464-8ce1f39a8414"),
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("f39e2070-1219-4429-be18-4a40434b136f"),
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("ffeda210-23b0-4a31-9635-f93aac974c6c"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("0a6dce21-5dbb-4ba2-bb04-438ae7436eee"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("c98640f2-439c-4327-9f90-a4a524f4dbbc"),
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("4709bcd1-2e03-4e29-9cb7-7f76c845dc25"),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("feae83d9-edd3-477c-a9d1-9e526799e5b2"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("65edf7ca-a53c-4ecf-8349-4cdf2efc83a7"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("5602e09a-13f4-49e9-9936-3eda332e2ada"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("820cb3ce-bc8f-448d-a242-76ccc21eafee"),
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("742065d4-341f-4a05-9651-6f375c61db96"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("a56ad084-f2c1-4fff-8c23-96b6cbec905a"),
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("669c8003-649d-4231-89fb-21c4dd37e9f7"),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("3cb423da-2018-4b3d-a375-6c0815698ea2"),
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("72690c9e-cd28-4a77-a65b-6e1cacfc32ff"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("417451e7-36c5-4f2d-9cee-f0180369194c"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("6a67f703-8ffc-4115-946a-2ddcd227af3c"),
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("6c10ec77-3728-4aff-b0df-ab1557feebf7"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("c2d82d64-3d64-4491-980e-ad4ab0eb97e1"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("3eece5c8-9797-4ce4-bc08-95a4837df775"),
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("8ea523e3-06d0-4f03-8328-18da53a8ce26"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("8efabece-7137-4d42-b563-35ad599376d3"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("ff249821-0da1-4c1b-9f29-b6ddcbca7818"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("3eef9bb2-2f5e-4643-96c3-ffc5d8efd54a"),
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = new Guid("9c83daec-3b38-45c4-919f-a2935b53d365"),
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("95c1a76c-936a-4956-a6c9-7c24b167bb4f"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("78d25f65-8e68-411b-9802-db6430c08a6a"),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("c58c6571-6d5c-4f63-9f0a-b62a84c35c37"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("243f552d-f3a0-4fe6-ae88-2d65b8bd05ec"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("ca904c88-313d-49ca-9ac4-dd2cfea32d32"),
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("16fc02d3-8f82-4436-accc-938ea8ede36e"),
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("f3a0996c-0567-4a2d-97a1-4b63ee5bbdc1"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("0de23e16-7a78-4b54-9d03-e1a1ab6cac70"),
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("8c37676e-2ac9-4d5b-a474-3f255f50fd25"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("b5b6a377-281d-4329-a16b-ae2e6ec03289"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("17374ad6-969c-46eb-a9a8-3b0f1a083716"),
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("6403d6cd-4a59-4e6e-b20f-541a757582e8"),
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("5284ac3c-6535-4f56-adb4-46889ea2208d"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("88269695-2455-45cf-9e7d-1ec77cb9655a"),
                            Name = "United Republic of Tanzania"
                        },
                        new
                        {
                            Id = new Guid("5e7db7ac-d5ea-498a-bbfb-3f60f763c4bf"),
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = new Guid("13a6aec8-59d2-436a-99f2-150660494617"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("d4f47e44-813f-46d3-814f-7f8c8f1c35cf"),
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("9da87ee4-c108-4d8e-b108-e7dcd7e459a5"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("f7f57776-2818-45a9-ac68-2ed1733ef22f"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("d5c33a7d-ec36-48fd-b2d7-5f15fd62056c"),
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = new Guid("89a560f5-9f33-48cb-b53e-8c073a29a613"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("7e72f195-e1a8-467b-a0ea-a4f05a7f5c95"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("02584afe-5d43-4836-b3a0-643bc4c1f81c"),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("StudyBuddy.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("StudyBuddy.Models.JobRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobRecommendations");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpertiseField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentorship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenteeId");

                    b.HasIndex("MentorId");

                    b.ToTable("Mentorships");
                });

            modelBuilder.Entity("StudyBuddy.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StudyBuddy.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("StudyBuddy.Models.StudyField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyFields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d789226-8950-4be0-b636-87efe68e4520"),
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = new Guid("46257d65-59bc-4055-b72d-bf722a629f48"),
                            Name = "Electrical Engineering"
                        },
                        new
                        {
                            Id = new Guid("34e8064f-2c36-4d4f-bbc9-adbed536701f"),
                            Name = "Business Administration"
                        },
                        new
                        {
                            Id = new Guid("4da2f441-14de-4810-ad85-425bd673a331"),
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = new Guid("16fd9fef-b4ea-48b2-bbf4-67a65d2bae22"),
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("75169622-ab89-4731-babd-51bd13529ff5"),
                            Name = "Law"
                        },
                        new
                        {
                            Id = new Guid("bf38d1ac-cc09-4df3-9201-ebeb895f119c"),
                            Name = "Biology"
                        },
                        new
                        {
                            Id = new Guid("1af6ab1b-4d8a-40cc-82ea-6a4485ef6032"),
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = new Guid("9b5950ae-0710-4be1-be89-74146dca33cf"),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("79fa333d-43df-43f7-be18-b2c4e2804adf"),
                            Name = "Economics"
                        },
                        new
                        {
                            Id = new Guid("6401b6fa-97f8-4d21-9a58-407b76567c78"),
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("26ffed59-09e3-499c-8105-5418607aa10c"),
                            Name = "Mechanical Engineering"
                        },
                        new
                        {
                            Id = new Guid("0992f676-cf34-457f-8bf3-422f051c25e5"),
                            Name = "Civil Engineering"
                        },
                        new
                        {
                            Id = new Guid("02c2b0ae-6bf7-4476-88cf-2b6a50f034a9"),
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("4cc21979-3b29-43b8-bdfc-b687c5ff876a"),
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = new Guid("4875c953-84e5-4b05-b991-86f38b2b84be"),
                            Name = "Nursing"
                        },
                        new
                        {
                            Id = new Guid("5bc2b473-9b3e-4984-953f-445225e8f9fa"),
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = new Guid("78a64809-cedf-4abd-8092-537bd0de84c3"),
                            Name = "Veterinary Medicine"
                        },
                        new
                        {
                            Id = new Guid("8a8e7452-e442-4aa9-abc8-b7fee0c0ad2e"),
                            Name = "Environmental Science"
                        },
                        new
                        {
                            Id = new Guid("de67a4fd-d042-4940-b49f-3aa8e124c536"),
                            Name = "Sociology"
                        },
                        new
                        {
                            Id = new Guid("661828ff-6be0-4e28-a8a5-017879bec087"),
                            Name = "Anthropology"
                        },
                        new
                        {
                            Id = new Guid("57d96d80-6f27-45b7-975e-11e4c81677fb"),
                            Name = "Political Science"
                        },
                        new
                        {
                            Id = new Guid("bc36e196-572c-4b8d-82d1-d2fc0971c653"),
                            Name = "International Relations"
                        },
                        new
                        {
                            Id = new Guid("57a4c1ee-43ab-4a6c-ad39-90f568ed81e7"),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("211e577c-63df-4015-9ad1-698c1e05b969"),
                            Name = "Special Education"
                        },
                        new
                        {
                            Id = new Guid("5dc6e3f0-5b0f-491c-926c-f2e8e9086e54"),
                            Name = "Linguistics"
                        },
                        new
                        {
                            Id = new Guid("0a8e70b6-4688-490b-93ab-85c710f0481b"),
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = new Guid("43467185-ea34-4559-9fa0-04fdd8796d9d"),
                            Name = "Theology"
                        },
                        new
                        {
                            Id = new Guid("b1cc3ef3-a844-4beb-8b1b-a8596d5dc737"),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("7cbacd2a-c74c-4916-a9d7-a3c44db78840"),
                            Name = "Art History"
                        },
                        new
                        {
                            Id = new Guid("b6a76d13-995f-44f4-828e-587ad3e8071d"),
                            Name = "Visual Arts"
                        },
                        new
                        {
                            Id = new Guid("57491336-0088-4e78-9260-a20a0c4338e5"),
                            Name = "Film Studies"
                        },
                        new
                        {
                            Id = new Guid("d6886980-1f75-488c-aba3-c95a4e839c15"),
                            Name = "Theater"
                        },
                        new
                        {
                            Id = new Guid("b4a8abc9-575f-45b6-95cf-6253ce7b764c"),
                            Name = "Communication"
                        },
                        new
                        {
                            Id = new Guid("7f571b9b-9c99-49e5-850c-1fbdc3944a9c"),
                            Name = "Journalism"
                        },
                        new
                        {
                            Id = new Guid("96b0f370-55a9-4c60-b3fc-045a9c469367"),
                            Name = "Public Relations"
                        },
                        new
                        {
                            Id = new Guid("332f4eed-8be0-4b12-a2d6-fda9c06503f6"),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("67615b65-d43c-4d26-8014-9f783c4113e8"),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("0f792a72-5361-4995-9881-5501d920db53"),
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("106bfc12-2226-4630-8a0f-814940ac0b74"),
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("a868f8e4-6264-43e3-adad-0b44fbe779ab"),
                            Name = "Supply Chain Management"
                        },
                        new
                        {
                            Id = new Guid("82b7cf01-15d8-42bb-8c19-287b98f5c6e2"),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("6705ae0a-eacd-4680-92ff-af97f38c0d5a"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("26bd11fc-1530-43fb-8369-1f4ba77c39eb"),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("99495665-01a5-4aad-a120-1b93f2b3c99f"),
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = new Guid("28982941-c6bc-4711-b0ec-1c86d07c4720"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("7c549bcd-c1ed-4808-ace6-3a5dadddd9e5"),
                            Name = "DevOps Engineering"
                        },
                        new
                        {
                            Id = new Guid("97c92255-d9a9-4cd5-91cb-4991c4d25036"),
                            Name = "Fullstack Development"
                        },
                        new
                        {
                            Id = new Guid("845c5c74-f35d-40cf-be2c-6a1f677d9d91"),
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("4b3f4521-0d1f-42fe-8a89-748dc1ff4c85"),
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("48ebfdda-3e10-4605-9403-3fd077fa5c5e"),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("67d6b340-c553-4aab-bd2c-70b8cfea9b19"),
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = new Guid("c0cd563c-4b86-4cb8-9fc1-b61039662b06"),
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("ea2ea1d9-dd12-4e64-9469-03c30c2c143c"),
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("ae052539-012b-49e7-ab4d-ec00eb13694f"),
                            Name = "Animation and Multimedia"
                        },
                        new
                        {
                            Id = new Guid("9a78ce7c-29ba-49c7-99d1-fc2e1ce77305"),
                            Name = "Interior Design"
                        },
                        new
                        {
                            Id = new Guid("a6f13c6f-a898-440d-a3f1-2156054f612f"),
                            Name = "Fashion Design"
                        },
                        new
                        {
                            Id = new Guid("08634721-ef6e-4b68-9256-a2c5128ac9d2"),
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("16f873f2-ce7c-4434-9deb-2a5db5236f97"),
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("efdef7a7-ade5-43a1-8e14-3886b5d8d9a8"),
                            Name = "E-commerce"
                        },
                        new
                        {
                            Id = new Guid("edb68350-868c-4ccb-978d-431841bb5a1f"),
                            Name = "Business Intelligence"
                        },
                        new
                        {
                            Id = new Guid("5ab209cb-f2c3-44cb-8a5e-426bd6120119"),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("9a7a6d95-6835-4a28-9458-37a063db52d9"),
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyField")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e66f9e6-e03d-4912-a05a-e28a1f7f7118"),
                            City = "Tel Aviv",
                            Country = "Israel",
                            CreatedAt = new DateTime(2025, 5, 3, 11, 42, 3, 470, DateTimeKind.Utc).AddTicks(1851),
                            Email = "admin1@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "One",
                            Location = "Israel",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c1c8016d-502d-41b4-b559-ce7791e818a9"),
                            City = "New York",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 5, 3, 11, 42, 3, 475, DateTimeKind.Utc).AddTicks(6663),
                            Email = "admin2@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "Two",
                            Location = "USA",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("6d0b4e0d-0167-49dd-a2b5-808fcaea4345"),
                            City = "London",
                            Country = "UK",
                            CreatedAt = new DateTime(2025, 5, 3, 11, 42, 3, 475, DateTimeKind.Utc).AddTicks(7110),
                            Email = "admin3@studybuddy.com",
                            FirstName = "Admin",
                            LastName = "Three",
                            Location = "UK",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("LeaderboardEntry", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Like", b =>
                {
                    b.HasOne("StudyBuddy.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Activity", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.ChatMessage", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StudyBuddy.Models.Comment", b =>
                {
                    b.HasOne("StudyBuddy.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.HasOne("StudyBuddy.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.StudyField", "StudyField")
                        .WithMany()
                        .HasForeignKey("StudyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("StudyBuddy.Models.Friendship", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentor", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Mentorship", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "Mentee")
                        .WithMany()
                        .HasForeignKey("MenteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Models.User", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("StudyBuddy.Models.Notification", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.Post", b =>
                {
                    b.HasOne("StudyBuddy.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.HasOne("StudyBuddy.Models.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");
                });

            modelBuilder.Entity("StudyBuddy.Models.Community", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("StudyBuddy.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("StudyBuddy.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Friends");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
